apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
  labels:
    app: sodeep-ai-stage
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
parameters:
  type: pd-standard
  replication-type: none
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reddis-pv-volume
  labels:
    type: local
    app: sodeep-ai-stage
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/redis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reddis-pv-claim
  labels:
    app: sodeep-ai-stage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi